executors:
  node:
    parameters:
      image:
        type: string
        default: "lts"
    docker:
      - image: cimg/node:<< parameters.image >>
        environment:
          TERM: xterm

aliases:
  e2e-executor: &e2e-executor
    docker:
      - image: cypress/browsers:node14.7.0-chrome84
        environment:
          TERM: xterm

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install Yarn Packages
      command: yarn install --frozen-lockfile --ignore-engines

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - /home/circleci/.cache

  store_results: &store_results
    store_test_results:
      path: results

  store_results_artifacts: &store_results_artifacts
    store_artifacts:
      path: results

  e2e-test-workflow: &e2e-test-workflow
    filters:
      branches:
        ignore:
          - /docs.+/
          - /www.+/
    requires:
      - unit_tests

commands:
  e2e-test:
    parameters:
      example-name:
        type: string
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Execute E2E script
          command: bash ./scripts/e2e-build.sh "<< parameters.example-name >>"
      - <<: *store_results
      - <<: *store_results_artifacts
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

version: 2.1

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Run ESLint
          command: yarn lint:ci
      - <<: *store_results
      - <<: *store_results_artifacts

  unit_tests:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Run Unit tests
          command: yarn test:ci --reporters=jest-junit
          environment:
            JEST_JUNIT_NAME: "Unit Tests"
            JEST_JUNIT_OUTPUT_DIR: "results/jest"
            JEST_JUNIT_OUTPUT_NAME: "result.xml"
      - <<: *store_results
      - <<: *store_results_artifacts

  e2e-test-cara:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: cara

  e2e-test-emma:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: emma

  e2e-test-emilia:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: emilia

  e2e-test-status-dashboard:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: status-dashboard

  e2e-test-graphql-playground:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: graphql-playground

  e2e-test-minimal-blog:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: minimal-blog

  e2e-test-styleguide:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: styleguide

  e2e-test-jodie:
    <<: *e2e-executor
    steps:
      - e2e-test:
          example-name: jodie

workflows:
  version: 2
  lint-test:
    jobs:
      - lint
      - unit_tests
      - e2e-test-cara:
          <<: *e2e-test-workflow
      - e2e-test-emilia:
          <<: *e2e-test-workflow
      - e2e-test-emma:
          <<: *e2e-test-workflow
      - e2e-test-status-dashboard:
          <<: *e2e-test-workflow
      - e2e-test-graphql-playground:
          <<: *e2e-test-workflow
      - e2e-test-minimal-blog:
          <<: *e2e-test-workflow
      - e2e-test-styleguide:
          <<: *e2e-test-workflow
      - e2e-test-jodie:
          <<: *e2e-test-workflow
