name: E2E Testing

on:
  pull_request:
    branches-ignore:
      - 'www/**'
      - 'renovate/www-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [cara, emilia, emma, graphql-playground, jodie, minimal-blog, status-dashboard, styleguide]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Test
        uses: cypress-io/github-action@v4
        with:
          record: true
          tag: ${{ matrix.containers }}
          spec: cypress/e2e/${{ matrix.containers }}.ts
          browser: chrome
          build: yarn workspace ${{ matrix.containers }} build:cypress
          start: yarn workspace ${{ matrix.containers }} serve
          config: "baseUrl=http://localhost:9000"
          cache-key: node-${{ matrix.containers }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
          install-command: yarn --immutable --silent
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CIRCLECI_KEY: ${{ secrets.CIRCLECI_KEY }}
          NETLIFY_ACCESS_KEY: ${{ secrets.NETLIFY_ACCESS_KEY }}