name: Unit Testing

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Run ESLint
        run: yarn lint
      - name: Run Vitest
        run: yarn test:ci
      # Don't run typechecking until Theme UI is updated to support new JSX syntax in 5.1
      # see https://github.com/system-ui/theme-ui/pull/2432
      # - name: Run TypeScript
      #  run: yarn typecheck:ci